spring.application.name=practice
# PostgresSQL database URL
spring.datasource.url=jdbc:postgresql://aws-0-ap-south-1.pooler.supabase.com:5432/postgres?user=postgres.yztpigyzwqdgqkglzeol&password=138717

# Database username and password
spring.datasource.username=postgres.yztpigyzwqdgqkglzeol
spring.datasource.password=138717

# Hibernate properties
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.security.user.name=user

logging.level.org.springframework.web.cors=DEBUG

security.jwt.secret-key=a995e04b52f13b5dc001c97e218ba5ab34672848cc06a22bdd272722dff50217
# 1h in millisecond
security.jwt.expiration-time=3600000
security.jwt.refresh.expiration-time=604800000
server.port=8081


server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=false
